name: easyvv
channels:
    - pytorch
    - nvidia
    - conda-forge
    - defaults

dependencies:
    - python>=3.10
      # pytorch3d does not support pytorch 1.13 yet
      # so we install 1.12.1 for now
    - pytorch>=1.13
    - pytorch-cuda>=11.6
    - torchvision
    - torchaudio

    - git
    - vim
    - cmake
    - conda-forge::ffmpeg
    - conda-forge::ncurses # vim: /home/xuzhen/miniconda3/envs/phdeform/bin/../lib/libtinfo.so.6: no version information available (required by vim)

    - pip
      # - pip:
      # - -r requirements.txt


# How to create the environment from scratch
# mamba create -n easyvv "python>=3.10" -y
# mamba env update # conda only supports environment.yml instead of environment.yaml (yaml recommended)
# cat requirements.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 pip install