# # use blender to render raw `hdf5` format results
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000000.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_00/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000001.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_01/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000002.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_02/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000003.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_03/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000004.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_04/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000005.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_05/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000006.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_06/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000007.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_07/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000008.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_08/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000009.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_09/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000010.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_10/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000011.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_11/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000012.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_12/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000013.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_13/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000014.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_14/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000015.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_15/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000016.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_16/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000017.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_17/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000018.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_18/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000019.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_19/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000020.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_20/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000021.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_21/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000022.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_22/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000023.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_23/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000024.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_24/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000025.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_25/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000026.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_26/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000027.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_27/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000028.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_28/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000029.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_29/hdf5
blenderproc run human_only_renderer.py --digital_human_path /home/xietao/data/synthetic_human/nathan/object/000030.obj --digital_human_config ./configs/digital_nathan_configs.json --camera_param_path ./configs/camera_parameters.json --camera_poses_path ./configs/camera_positions --output_dir ./output/only_nathan/frame_30/hdf5

# use `hd5tojpg.py` to transform
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_00/hdf5 --img_folder ./output/only_nathan/frame_00/images --msk_folder ./output/only_nathan/frame_00/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_01/hdf5 --img_folder ./output/only_nathan/frame_01/images --msk_folder ./output/only_nathan/frame_01/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_02/hdf5 --img_folder ./output/only_nathan/frame_02/images --msk_folder ./output/only_nathan/frame_02/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_03/hdf5 --img_folder ./output/only_nathan/frame_03/images --msk_folder ./output/only_nathan/frame_03/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_04/hdf5 --img_folder ./output/only_nathan/frame_04/images --msk_folder ./output/only_nathan/frame_04/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_05/hdf5 --img_folder ./output/only_nathan/frame_05/images --msk_folder ./output/only_nathan/frame_05/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_06/hdf5 --img_folder ./output/only_nathan/frame_06/images --msk_folder ./output/only_nathan/frame_06/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_07/hdf5 --img_folder ./output/only_nathan/frame_07/images --msk_folder ./output/only_nathan/frame_07/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_08/hdf5 --img_folder ./output/only_nathan/frame_08/images --msk_folder ./output/only_nathan/frame_08/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_09/hdf5 --img_folder ./output/only_nathan/frame_09/images --msk_folder ./output/only_nathan/frame_09/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_10/hdf5 --img_folder ./output/only_nathan/frame_10/images --msk_folder ./output/only_nathan/frame_10/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_11/hdf5 --img_folder ./output/only_nathan/frame_11/images --msk_folder ./output/only_nathan/frame_11/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_12/hdf5 --img_folder ./output/only_nathan/frame_12/images --msk_folder ./output/only_nathan/frame_12/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_13/hdf5 --img_folder ./output/only_nathan/frame_13/images --msk_folder ./output/only_nathan/frame_13/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_14/hdf5 --img_folder ./output/only_nathan/frame_14/images --msk_folder ./output/only_nathan/frame_14/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_15/hdf5 --img_folder ./output/only_nathan/frame_15/images --msk_folder ./output/only_nathan/frame_15/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_16/hdf5 --img_folder ./output/only_nathan/frame_16/images --msk_folder ./output/only_nathan/frame_16/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_17/hdf5 --img_folder ./output/only_nathan/frame_17/images --msk_folder ./output/only_nathan/frame_17/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_18/hdf5 --img_folder ./output/only_nathan/frame_18/images --msk_folder ./output/only_nathan/frame_18/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_19/hdf5 --img_folder ./output/only_nathan/frame_19/images --msk_folder ./output/only_nathan/frame_19/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_20/hdf5 --img_folder ./output/only_nathan/frame_20/images --msk_folder ./output/only_nathan/frame_20/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_21/hdf5 --img_folder ./output/only_nathan/frame_21/images --msk_folder ./output/only_nathan/frame_21/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_22/hdf5 --img_folder ./output/only_nathan/frame_22/images --msk_folder ./output/only_nathan/frame_22/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_23/hdf5 --img_folder ./output/only_nathan/frame_23/images --msk_folder ./output/only_nathan/frame_23/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_24/hdf5 --img_folder ./output/only_nathan/frame_24/images --msk_folder ./output/only_nathan/frame_24/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_25/hdf5 --img_folder ./output/only_nathan/frame_25/images --msk_folder ./output/only_nathan/frame_25/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_26/hdf5 --img_folder ./output/only_nathan/frame_26/images --msk_folder ./output/only_nathan/frame_26/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_27/hdf5 --img_folder ./output/only_nathan/frame_27/images --msk_folder ./output/only_nathan/frame_27/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_28/hdf5 --img_folder ./output/only_nathan/frame_28/images --msk_folder ./output/only_nathan/frame_28/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_29/hdf5 --img_folder ./output/only_nathan/frame_29/images --msk_folder ./output/only_nathan/frame_29/mask
python ./scripts/hd5tojpg_plus_mask.py --raw_folder ./output/only_nathan/frame_30/hdf5 --img_folder ./output/only_nathan/frame_30/images --msk_folder ./output/only_nathan/frame_30/mask

# rename and move all the rendered human images
mkdir -p ./data/synthetic_human/nathan/images/00
mkdir -p ./data/synthetic_human/nathan/mask/00
mkdir -p ./data/synthetic_human/nathan/images/01
mkdir -p ./data/synthetic_human/nathan/mask/01
mkdir -p ./data/synthetic_human/nathan/images/02
mkdir -p ./data/synthetic_human/nathan/mask/02
mkdir -p ./data/synthetic_human/nathan/images/03
mkdir -p ./data/synthetic_human/nathan/mask/03
mkdir -p ./data/synthetic_human/nathan/images/04
mkdir -p ./data/synthetic_human/nathan/mask/04
mkdir -p ./data/synthetic_human/nathan/images/05
mkdir -p ./data/synthetic_human/nathan/mask/05
mkdir -p ./data/synthetic_human/nathan/images/06
mkdir -p ./data/synthetic_human/nathan/mask/06
mkdir -p ./data/synthetic_human/nathan/images/07
mkdir -p ./data/synthetic_human/nathan/mask/07
mkdir -p ./data/synthetic_human/nathan/images/08
mkdir -p ./data/synthetic_human/nathan/mask/08
mkdir -p ./data/synthetic_human/nathan/images/09
mkdir -p ./data/synthetic_human/nathan/mask/09
cp ./output/only_nathan/frame_00/images/0.jpg ./data/synthetic_human/nathan/images/00/000000.jpg
cp ./output/only_nathan/frame_00/mask/0.png ./data/synthetic_human/nathan/mask/00/000000.png
cp ./output/only_nathan/frame_00/images/1.jpg ./data/synthetic_human/nathan/images/01/000000.jpg
cp ./output/only_nathan/frame_00/mask/1.png ./data/synthetic_human/nathan/mask/01/000000.png
cp ./output/only_nathan/frame_00/images/2.jpg ./data/synthetic_human/nathan/images/02/000000.jpg
cp ./output/only_nathan/frame_00/mask/2.png ./data/synthetic_human/nathan/mask/02/000000.png
cp ./output/only_nathan/frame_00/images/3.jpg ./data/synthetic_human/nathan/images/03/000000.jpg
cp ./output/only_nathan/frame_00/mask/3.png ./data/synthetic_human/nathan/mask/03/000000.png
cp ./output/only_nathan/frame_00/images/4.jpg ./data/synthetic_human/nathan/images/04/000000.jpg
cp ./output/only_nathan/frame_00/mask/4.png ./data/synthetic_human/nathan/mask/04/000000.png
cp ./output/only_nathan/frame_00/images/5.jpg ./data/synthetic_human/nathan/images/05/000000.jpg
cp ./output/only_nathan/frame_00/mask/5.png ./data/synthetic_human/nathan/mask/05/000000.png
cp ./output/only_nathan/frame_00/images/6.jpg ./data/synthetic_human/nathan/images/06/000000.jpg
cp ./output/only_nathan/frame_00/mask/6.png ./data/synthetic_human/nathan/mask/06/000000.png
cp ./output/only_nathan/frame_00/images/7.jpg ./data/synthetic_human/nathan/images/07/000000.jpg
cp ./output/only_nathan/frame_00/mask/7.png ./data/synthetic_human/nathan/mask/07/000000.png
cp ./output/only_nathan/frame_00/images/8.jpg ./data/synthetic_human/nathan/images/08/000000.jpg
cp ./output/only_nathan/frame_00/mask/8.png ./data/synthetic_human/nathan/mask/08/000000.png
cp ./output/only_nathan/frame_00/images/9.jpg ./data/synthetic_human/nathan/images/09/000000.jpg
cp ./output/only_nathan/frame_00/mask/9.png ./data/synthetic_human/nathan/mask/09/000000.png
cp ./output/only_nathan/frame_01/images/0.jpg ./data/synthetic_human/nathan/images/00/000001.jpg
cp ./output/only_nathan/frame_01/mask/0.png ./data/synthetic_human/nathan/mask/00/000001.png
cp ./output/only_nathan/frame_01/images/1.jpg ./data/synthetic_human/nathan/images/01/000001.jpg
cp ./output/only_nathan/frame_01/mask/1.png ./data/synthetic_human/nathan/mask/01/000001.png
cp ./output/only_nathan/frame_01/images/2.jpg ./data/synthetic_human/nathan/images/02/000001.jpg
cp ./output/only_nathan/frame_01/mask/2.png ./data/synthetic_human/nathan/mask/02/000001.png
cp ./output/only_nathan/frame_01/images/3.jpg ./data/synthetic_human/nathan/images/03/000001.jpg
cp ./output/only_nathan/frame_01/mask/3.png ./data/synthetic_human/nathan/mask/03/000001.png
cp ./output/only_nathan/frame_01/images/4.jpg ./data/synthetic_human/nathan/images/04/000001.jpg
cp ./output/only_nathan/frame_01/mask/4.png ./data/synthetic_human/nathan/mask/04/000001.png
cp ./output/only_nathan/frame_01/images/5.jpg ./data/synthetic_human/nathan/images/05/000001.jpg
cp ./output/only_nathan/frame_01/mask/5.png ./data/synthetic_human/nathan/mask/05/000001.png
cp ./output/only_nathan/frame_01/images/6.jpg ./data/synthetic_human/nathan/images/06/000001.jpg
cp ./output/only_nathan/frame_01/mask/6.png ./data/synthetic_human/nathan/mask/06/000001.png
cp ./output/only_nathan/frame_01/images/7.jpg ./data/synthetic_human/nathan/images/07/000001.jpg
cp ./output/only_nathan/frame_01/mask/7.png ./data/synthetic_human/nathan/mask/07/000001.png
cp ./output/only_nathan/frame_01/images/8.jpg ./data/synthetic_human/nathan/images/08/000001.jpg
cp ./output/only_nathan/frame_01/mask/8.png ./data/synthetic_human/nathan/mask/08/000001.png
cp ./output/only_nathan/frame_01/images/9.jpg ./data/synthetic_human/nathan/images/09/000001.jpg
cp ./output/only_nathan/frame_01/mask/9.png ./data/synthetic_human/nathan/mask/09/000001.png
cp ./output/only_nathan/frame_02/images/0.jpg ./data/synthetic_human/nathan/images/00/000002.jpg
cp ./output/only_nathan/frame_02/mask/0.png ./data/synthetic_human/nathan/mask/00/000002.png
cp ./output/only_nathan/frame_02/images/1.jpg ./data/synthetic_human/nathan/images/01/000002.jpg
cp ./output/only_nathan/frame_02/mask/1.png ./data/synthetic_human/nathan/mask/01/000002.png
cp ./output/only_nathan/frame_02/images/2.jpg ./data/synthetic_human/nathan/images/02/000002.jpg
cp ./output/only_nathan/frame_02/mask/2.png ./data/synthetic_human/nathan/mask/02/000002.png
cp ./output/only_nathan/frame_02/images/3.jpg ./data/synthetic_human/nathan/images/03/000002.jpg
cp ./output/only_nathan/frame_02/mask/3.png ./data/synthetic_human/nathan/mask/03/000002.png
cp ./output/only_nathan/frame_02/images/4.jpg ./data/synthetic_human/nathan/images/04/000002.jpg
cp ./output/only_nathan/frame_02/mask/4.png ./data/synthetic_human/nathan/mask/04/000002.png
cp ./output/only_nathan/frame_02/images/5.jpg ./data/synthetic_human/nathan/images/05/000002.jpg
cp ./output/only_nathan/frame_02/mask/5.png ./data/synthetic_human/nathan/mask/05/000002.png
cp ./output/only_nathan/frame_02/images/6.jpg ./data/synthetic_human/nathan/images/06/000002.jpg
cp ./output/only_nathan/frame_02/mask/6.png ./data/synthetic_human/nathan/mask/06/000002.png
cp ./output/only_nathan/frame_02/images/7.jpg ./data/synthetic_human/nathan/images/07/000002.jpg
cp ./output/only_nathan/frame_02/mask/7.png ./data/synthetic_human/nathan/mask/07/000002.png
cp ./output/only_nathan/frame_02/images/8.jpg ./data/synthetic_human/nathan/images/08/000002.jpg
cp ./output/only_nathan/frame_02/mask/8.png ./data/synthetic_human/nathan/mask/08/000002.png
cp ./output/only_nathan/frame_02/images/9.jpg ./data/synthetic_human/nathan/images/09/000002.jpg
cp ./output/only_nathan/frame_02/mask/9.png ./data/synthetic_human/nathan/mask/09/000002.png
cp ./output/only_nathan/frame_03/images/0.jpg ./data/synthetic_human/nathan/images/00/000003.jpg
cp ./output/only_nathan/frame_03/mask/0.png ./data/synthetic_human/nathan/mask/00/000003.png
cp ./output/only_nathan/frame_03/images/1.jpg ./data/synthetic_human/nathan/images/01/000003.jpg
cp ./output/only_nathan/frame_03/mask/1.png ./data/synthetic_human/nathan/mask/01/000003.png
cp ./output/only_nathan/frame_03/images/2.jpg ./data/synthetic_human/nathan/images/02/000003.jpg
cp ./output/only_nathan/frame_03/mask/2.png ./data/synthetic_human/nathan/mask/02/000003.png
cp ./output/only_nathan/frame_03/images/3.jpg ./data/synthetic_human/nathan/images/03/000003.jpg
cp ./output/only_nathan/frame_03/mask/3.png ./data/synthetic_human/nathan/mask/03/000003.png
cp ./output/only_nathan/frame_03/images/4.jpg ./data/synthetic_human/nathan/images/04/000003.jpg
cp ./output/only_nathan/frame_03/mask/4.png ./data/synthetic_human/nathan/mask/04/000003.png
cp ./output/only_nathan/frame_03/images/5.jpg ./data/synthetic_human/nathan/images/05/000003.jpg
cp ./output/only_nathan/frame_03/mask/5.png ./data/synthetic_human/nathan/mask/05/000003.png
cp ./output/only_nathan/frame_03/images/6.jpg ./data/synthetic_human/nathan/images/06/000003.jpg
cp ./output/only_nathan/frame_03/mask/6.png ./data/synthetic_human/nathan/mask/06/000003.png
cp ./output/only_nathan/frame_03/images/7.jpg ./data/synthetic_human/nathan/images/07/000003.jpg
cp ./output/only_nathan/frame_03/mask/7.png ./data/synthetic_human/nathan/mask/07/000003.png
cp ./output/only_nathan/frame_03/images/8.jpg ./data/synthetic_human/nathan/images/08/000003.jpg
cp ./output/only_nathan/frame_03/mask/8.png ./data/synthetic_human/nathan/mask/08/000003.png
cp ./output/only_nathan/frame_03/images/9.jpg ./data/synthetic_human/nathan/images/09/000003.jpg
cp ./output/only_nathan/frame_03/mask/9.png ./data/synthetic_human/nathan/mask/09/000003.png
cp ./output/only_nathan/frame_04/images/0.jpg ./data/synthetic_human/nathan/images/00/000004.jpg
cp ./output/only_nathan/frame_04/mask/0.png ./data/synthetic_human/nathan/mask/00/000004.png
cp ./output/only_nathan/frame_04/images/1.jpg ./data/synthetic_human/nathan/images/01/000004.jpg
cp ./output/only_nathan/frame_04/mask/1.png ./data/synthetic_human/nathan/mask/01/000004.png
cp ./output/only_nathan/frame_04/images/2.jpg ./data/synthetic_human/nathan/images/02/000004.jpg
cp ./output/only_nathan/frame_04/mask/2.png ./data/synthetic_human/nathan/mask/02/000004.png
cp ./output/only_nathan/frame_04/images/3.jpg ./data/synthetic_human/nathan/images/03/000004.jpg
cp ./output/only_nathan/frame_04/mask/3.png ./data/synthetic_human/nathan/mask/03/000004.png
cp ./output/only_nathan/frame_04/images/4.jpg ./data/synthetic_human/nathan/images/04/000004.jpg
cp ./output/only_nathan/frame_04/mask/4.png ./data/synthetic_human/nathan/mask/04/000004.png
cp ./output/only_nathan/frame_04/images/5.jpg ./data/synthetic_human/nathan/images/05/000004.jpg
cp ./output/only_nathan/frame_04/mask/5.png ./data/synthetic_human/nathan/mask/05/000004.png
cp ./output/only_nathan/frame_04/images/6.jpg ./data/synthetic_human/nathan/images/06/000004.jpg
cp ./output/only_nathan/frame_04/mask/6.png ./data/synthetic_human/nathan/mask/06/000004.png
cp ./output/only_nathan/frame_04/images/7.jpg ./data/synthetic_human/nathan/images/07/000004.jpg
cp ./output/only_nathan/frame_04/mask/7.png ./data/synthetic_human/nathan/mask/07/000004.png
cp ./output/only_nathan/frame_04/images/8.jpg ./data/synthetic_human/nathan/images/08/000004.jpg
cp ./output/only_nathan/frame_04/mask/8.png ./data/synthetic_human/nathan/mask/08/000004.png
cp ./output/only_nathan/frame_04/images/9.jpg ./data/synthetic_human/nathan/images/09/000004.jpg
cp ./output/only_nathan/frame_04/mask/9.png ./data/synthetic_human/nathan/mask/09/000004.png
cp ./output/only_nathan/frame_05/images/0.jpg ./data/synthetic_human/nathan/images/00/000005.jpg
cp ./output/only_nathan/frame_05/mask/0.png ./data/synthetic_human/nathan/mask/00/000005.png
cp ./output/only_nathan/frame_05/images/1.jpg ./data/synthetic_human/nathan/images/01/000005.jpg
cp ./output/only_nathan/frame_05/mask/1.png ./data/synthetic_human/nathan/mask/01/000005.png
cp ./output/only_nathan/frame_05/images/2.jpg ./data/synthetic_human/nathan/images/02/000005.jpg
cp ./output/only_nathan/frame_05/mask/2.png ./data/synthetic_human/nathan/mask/02/000005.png
cp ./output/only_nathan/frame_05/images/3.jpg ./data/synthetic_human/nathan/images/03/000005.jpg
cp ./output/only_nathan/frame_05/mask/3.png ./data/synthetic_human/nathan/mask/03/000005.png
cp ./output/only_nathan/frame_05/images/4.jpg ./data/synthetic_human/nathan/images/04/000005.jpg
cp ./output/only_nathan/frame_05/mask/4.png ./data/synthetic_human/nathan/mask/04/000005.png
cp ./output/only_nathan/frame_05/images/5.jpg ./data/synthetic_human/nathan/images/05/000005.jpg
cp ./output/only_nathan/frame_05/mask/5.png ./data/synthetic_human/nathan/mask/05/000005.png
cp ./output/only_nathan/frame_05/images/6.jpg ./data/synthetic_human/nathan/images/06/000005.jpg
cp ./output/only_nathan/frame_05/mask/6.png ./data/synthetic_human/nathan/mask/06/000005.png
cp ./output/only_nathan/frame_05/images/7.jpg ./data/synthetic_human/nathan/images/07/000005.jpg
cp ./output/only_nathan/frame_05/mask/7.png ./data/synthetic_human/nathan/mask/07/000005.png
cp ./output/only_nathan/frame_05/images/8.jpg ./data/synthetic_human/nathan/images/08/000005.jpg
cp ./output/only_nathan/frame_05/mask/8.png ./data/synthetic_human/nathan/mask/08/000005.png
cp ./output/only_nathan/frame_05/images/9.jpg ./data/synthetic_human/nathan/images/09/000005.jpg
cp ./output/only_nathan/frame_05/mask/9.png ./data/synthetic_human/nathan/mask/09/000005.png
cp ./output/only_nathan/frame_06/images/0.jpg ./data/synthetic_human/nathan/images/00/000006.jpg
cp ./output/only_nathan/frame_06/mask/0.png ./data/synthetic_human/nathan/mask/00/000006.png
cp ./output/only_nathan/frame_06/images/1.jpg ./data/synthetic_human/nathan/images/01/000006.jpg
cp ./output/only_nathan/frame_06/mask/1.png ./data/synthetic_human/nathan/mask/01/000006.png
cp ./output/only_nathan/frame_06/images/2.jpg ./data/synthetic_human/nathan/images/02/000006.jpg
cp ./output/only_nathan/frame_06/mask/2.png ./data/synthetic_human/nathan/mask/02/000006.png
cp ./output/only_nathan/frame_06/images/3.jpg ./data/synthetic_human/nathan/images/03/000006.jpg
cp ./output/only_nathan/frame_06/mask/3.png ./data/synthetic_human/nathan/mask/03/000006.png
cp ./output/only_nathan/frame_06/images/4.jpg ./data/synthetic_human/nathan/images/04/000006.jpg
cp ./output/only_nathan/frame_06/mask/4.png ./data/synthetic_human/nathan/mask/04/000006.png
cp ./output/only_nathan/frame_06/images/5.jpg ./data/synthetic_human/nathan/images/05/000006.jpg
cp ./output/only_nathan/frame_06/mask/5.png ./data/synthetic_human/nathan/mask/05/000006.png
cp ./output/only_nathan/frame_06/images/6.jpg ./data/synthetic_human/nathan/images/06/000006.jpg
cp ./output/only_nathan/frame_06/mask/6.png ./data/synthetic_human/nathan/mask/06/000006.png
cp ./output/only_nathan/frame_06/images/7.jpg ./data/synthetic_human/nathan/images/07/000006.jpg
cp ./output/only_nathan/frame_06/mask/7.png ./data/synthetic_human/nathan/mask/07/000006.png
cp ./output/only_nathan/frame_06/images/8.jpg ./data/synthetic_human/nathan/images/08/000006.jpg
cp ./output/only_nathan/frame_06/mask/8.png ./data/synthetic_human/nathan/mask/08/000006.png
cp ./output/only_nathan/frame_06/images/9.jpg ./data/synthetic_human/nathan/images/09/000006.jpg
cp ./output/only_nathan/frame_06/mask/9.png ./data/synthetic_human/nathan/mask/09/000006.png
cp ./output/only_nathan/frame_07/images/0.jpg ./data/synthetic_human/nathan/images/00/000007.jpg
cp ./output/only_nathan/frame_07/mask/0.png ./data/synthetic_human/nathan/mask/00/000007.png
cp ./output/only_nathan/frame_07/images/1.jpg ./data/synthetic_human/nathan/images/01/000007.jpg
cp ./output/only_nathan/frame_07/mask/1.png ./data/synthetic_human/nathan/mask/01/000007.png
cp ./output/only_nathan/frame_07/images/2.jpg ./data/synthetic_human/nathan/images/02/000007.jpg
cp ./output/only_nathan/frame_07/mask/2.png ./data/synthetic_human/nathan/mask/02/000007.png
cp ./output/only_nathan/frame_07/images/3.jpg ./data/synthetic_human/nathan/images/03/000007.jpg
cp ./output/only_nathan/frame_07/mask/3.png ./data/synthetic_human/nathan/mask/03/000007.png
cp ./output/only_nathan/frame_07/images/4.jpg ./data/synthetic_human/nathan/images/04/000007.jpg
cp ./output/only_nathan/frame_07/mask/4.png ./data/synthetic_human/nathan/mask/04/000007.png
cp ./output/only_nathan/frame_07/images/5.jpg ./data/synthetic_human/nathan/images/05/000007.jpg
cp ./output/only_nathan/frame_07/mask/5.png ./data/synthetic_human/nathan/mask/05/000007.png
cp ./output/only_nathan/frame_07/images/6.jpg ./data/synthetic_human/nathan/images/06/000007.jpg
cp ./output/only_nathan/frame_07/mask/6.png ./data/synthetic_human/nathan/mask/06/000007.png
cp ./output/only_nathan/frame_07/images/7.jpg ./data/synthetic_human/nathan/images/07/000007.jpg
cp ./output/only_nathan/frame_07/mask/7.png ./data/synthetic_human/nathan/mask/07/000007.png
cp ./output/only_nathan/frame_07/images/8.jpg ./data/synthetic_human/nathan/images/08/000007.jpg
cp ./output/only_nathan/frame_07/mask/8.png ./data/synthetic_human/nathan/mask/08/000007.png
cp ./output/only_nathan/frame_07/images/9.jpg ./data/synthetic_human/nathan/images/09/000007.jpg
cp ./output/only_nathan/frame_07/mask/9.png ./data/synthetic_human/nathan/mask/09/000007.png
cp ./output/only_nathan/frame_08/images/0.jpg ./data/synthetic_human/nathan/images/00/000008.jpg
cp ./output/only_nathan/frame_08/mask/0.png ./data/synthetic_human/nathan/mask/00/000008.png
cp ./output/only_nathan/frame_08/images/1.jpg ./data/synthetic_human/nathan/images/01/000008.jpg
cp ./output/only_nathan/frame_08/mask/1.png ./data/synthetic_human/nathan/mask/01/000008.png
cp ./output/only_nathan/frame_08/images/2.jpg ./data/synthetic_human/nathan/images/02/000008.jpg
cp ./output/only_nathan/frame_08/mask/2.png ./data/synthetic_human/nathan/mask/02/000008.png
cp ./output/only_nathan/frame_08/images/3.jpg ./data/synthetic_human/nathan/images/03/000008.jpg
cp ./output/only_nathan/frame_08/mask/3.png ./data/synthetic_human/nathan/mask/03/000008.png
cp ./output/only_nathan/frame_08/images/4.jpg ./data/synthetic_human/nathan/images/04/000008.jpg
cp ./output/only_nathan/frame_08/mask/4.png ./data/synthetic_human/nathan/mask/04/000008.png
cp ./output/only_nathan/frame_08/images/5.jpg ./data/synthetic_human/nathan/images/05/000008.jpg
cp ./output/only_nathan/frame_08/mask/5.png ./data/synthetic_human/nathan/mask/05/000008.png
cp ./output/only_nathan/frame_08/images/6.jpg ./data/synthetic_human/nathan/images/06/000008.jpg
cp ./output/only_nathan/frame_08/mask/6.png ./data/synthetic_human/nathan/mask/06/000008.png
cp ./output/only_nathan/frame_08/images/7.jpg ./data/synthetic_human/nathan/images/07/000008.jpg
cp ./output/only_nathan/frame_08/mask/7.png ./data/synthetic_human/nathan/mask/07/000008.png
cp ./output/only_nathan/frame_08/images/8.jpg ./data/synthetic_human/nathan/images/08/000008.jpg
cp ./output/only_nathan/frame_08/mask/8.png ./data/synthetic_human/nathan/mask/08/000008.png
cp ./output/only_nathan/frame_08/images/9.jpg ./data/synthetic_human/nathan/images/09/000008.jpg
cp ./output/only_nathan/frame_08/mask/9.png ./data/synthetic_human/nathan/mask/09/000008.png
cp ./output/only_nathan/frame_09/images/0.jpg ./data/synthetic_human/nathan/images/00/000009.jpg
cp ./output/only_nathan/frame_09/mask/0.png ./data/synthetic_human/nathan/mask/00/000009.png
cp ./output/only_nathan/frame_09/images/1.jpg ./data/synthetic_human/nathan/images/01/000009.jpg
cp ./output/only_nathan/frame_09/mask/1.png ./data/synthetic_human/nathan/mask/01/000009.png
cp ./output/only_nathan/frame_09/images/2.jpg ./data/synthetic_human/nathan/images/02/000009.jpg
cp ./output/only_nathan/frame_09/mask/2.png ./data/synthetic_human/nathan/mask/02/000009.png
cp ./output/only_nathan/frame_09/images/3.jpg ./data/synthetic_human/nathan/images/03/000009.jpg
cp ./output/only_nathan/frame_09/mask/3.png ./data/synthetic_human/nathan/mask/03/000009.png
cp ./output/only_nathan/frame_09/images/4.jpg ./data/synthetic_human/nathan/images/04/000009.jpg
cp ./output/only_nathan/frame_09/mask/4.png ./data/synthetic_human/nathan/mask/04/000009.png
cp ./output/only_nathan/frame_09/images/5.jpg ./data/synthetic_human/nathan/images/05/000009.jpg
cp ./output/only_nathan/frame_09/mask/5.png ./data/synthetic_human/nathan/mask/05/000009.png
cp ./output/only_nathan/frame_09/images/6.jpg ./data/synthetic_human/nathan/images/06/000009.jpg
cp ./output/only_nathan/frame_09/mask/6.png ./data/synthetic_human/nathan/mask/06/000009.png
cp ./output/only_nathan/frame_09/images/7.jpg ./data/synthetic_human/nathan/images/07/000009.jpg
cp ./output/only_nathan/frame_09/mask/7.png ./data/synthetic_human/nathan/mask/07/000009.png
cp ./output/only_nathan/frame_09/images/8.jpg ./data/synthetic_human/nathan/images/08/000009.jpg
cp ./output/only_nathan/frame_09/mask/8.png ./data/synthetic_human/nathan/mask/08/000009.png
cp ./output/only_nathan/frame_09/images/9.jpg ./data/synthetic_human/nathan/images/09/000009.jpg
cp ./output/only_nathan/frame_09/mask/9.png ./data/synthetic_human/nathan/mask/09/000009.png
cp ./output/only_nathan/frame_10/images/0.jpg ./data/synthetic_human/nathan/images/00/000010.jpg
cp ./output/only_nathan/frame_10/mask/0.png ./data/synthetic_human/nathan/mask/00/000010.png
cp ./output/only_nathan/frame_10/images/1.jpg ./data/synthetic_human/nathan/images/01/000010.jpg
cp ./output/only_nathan/frame_10/mask/1.png ./data/synthetic_human/nathan/mask/01/000010.png
cp ./output/only_nathan/frame_10/images/2.jpg ./data/synthetic_human/nathan/images/02/000010.jpg
cp ./output/only_nathan/frame_10/mask/2.png ./data/synthetic_human/nathan/mask/02/000010.png
cp ./output/only_nathan/frame_10/images/3.jpg ./data/synthetic_human/nathan/images/03/000010.jpg
cp ./output/only_nathan/frame_10/mask/3.png ./data/synthetic_human/nathan/mask/03/000010.png
cp ./output/only_nathan/frame_10/images/4.jpg ./data/synthetic_human/nathan/images/04/000010.jpg
cp ./output/only_nathan/frame_10/mask/4.png ./data/synthetic_human/nathan/mask/04/000010.png
cp ./output/only_nathan/frame_10/images/5.jpg ./data/synthetic_human/nathan/images/05/000010.jpg
cp ./output/only_nathan/frame_10/mask/5.png ./data/synthetic_human/nathan/mask/05/000010.png
cp ./output/only_nathan/frame_10/images/6.jpg ./data/synthetic_human/nathan/images/06/000010.jpg
cp ./output/only_nathan/frame_10/mask/6.png ./data/synthetic_human/nathan/mask/06/000010.png
cp ./output/only_nathan/frame_10/images/7.jpg ./data/synthetic_human/nathan/images/07/000010.jpg
cp ./output/only_nathan/frame_10/mask/7.png ./data/synthetic_human/nathan/mask/07/000010.png
cp ./output/only_nathan/frame_10/images/8.jpg ./data/synthetic_human/nathan/images/08/000010.jpg
cp ./output/only_nathan/frame_10/mask/8.png ./data/synthetic_human/nathan/mask/08/000010.png
cp ./output/only_nathan/frame_10/images/9.jpg ./data/synthetic_human/nathan/images/09/000010.jpg
cp ./output/only_nathan/frame_10/mask/9.png ./data/synthetic_human/nathan/mask/09/000010.png
cp ./output/only_nathan/frame_11/images/0.jpg ./data/synthetic_human/nathan/images/00/000011.jpg
cp ./output/only_nathan/frame_11/mask/0.png ./data/synthetic_human/nathan/mask/00/000011.png
cp ./output/only_nathan/frame_11/images/1.jpg ./data/synthetic_human/nathan/images/01/000011.jpg
cp ./output/only_nathan/frame_11/mask/1.png ./data/synthetic_human/nathan/mask/01/000011.png
cp ./output/only_nathan/frame_11/images/2.jpg ./data/synthetic_human/nathan/images/02/000011.jpg
cp ./output/only_nathan/frame_11/mask/2.png ./data/synthetic_human/nathan/mask/02/000011.png
cp ./output/only_nathan/frame_11/images/3.jpg ./data/synthetic_human/nathan/images/03/000011.jpg
cp ./output/only_nathan/frame_11/mask/3.png ./data/synthetic_human/nathan/mask/03/000011.png
cp ./output/only_nathan/frame_11/images/4.jpg ./data/synthetic_human/nathan/images/04/000011.jpg
cp ./output/only_nathan/frame_11/mask/4.png ./data/synthetic_human/nathan/mask/04/000011.png
cp ./output/only_nathan/frame_11/images/5.jpg ./data/synthetic_human/nathan/images/05/000011.jpg
cp ./output/only_nathan/frame_11/mask/5.png ./data/synthetic_human/nathan/mask/05/000011.png
cp ./output/only_nathan/frame_11/images/6.jpg ./data/synthetic_human/nathan/images/06/000011.jpg
cp ./output/only_nathan/frame_11/mask/6.png ./data/synthetic_human/nathan/mask/06/000011.png
cp ./output/only_nathan/frame_11/images/7.jpg ./data/synthetic_human/nathan/images/07/000011.jpg
cp ./output/only_nathan/frame_11/mask/7.png ./data/synthetic_human/nathan/mask/07/000011.png
cp ./output/only_nathan/frame_11/images/8.jpg ./data/synthetic_human/nathan/images/08/000011.jpg
cp ./output/only_nathan/frame_11/mask/8.png ./data/synthetic_human/nathan/mask/08/000011.png
cp ./output/only_nathan/frame_11/images/9.jpg ./data/synthetic_human/nathan/images/09/000011.jpg
cp ./output/only_nathan/frame_11/mask/9.png ./data/synthetic_human/nathan/mask/09/000011.png
cp ./output/only_nathan/frame_12/images/0.jpg ./data/synthetic_human/nathan/images/00/000012.jpg
cp ./output/only_nathan/frame_12/mask/0.png ./data/synthetic_human/nathan/mask/00/000012.png
cp ./output/only_nathan/frame_12/images/1.jpg ./data/synthetic_human/nathan/images/01/000012.jpg
cp ./output/only_nathan/frame_12/mask/1.png ./data/synthetic_human/nathan/mask/01/000012.png
cp ./output/only_nathan/frame_12/images/2.jpg ./data/synthetic_human/nathan/images/02/000012.jpg
cp ./output/only_nathan/frame_12/mask/2.png ./data/synthetic_human/nathan/mask/02/000012.png
cp ./output/only_nathan/frame_12/images/3.jpg ./data/synthetic_human/nathan/images/03/000012.jpg
cp ./output/only_nathan/frame_12/mask/3.png ./data/synthetic_human/nathan/mask/03/000012.png
cp ./output/only_nathan/frame_12/images/4.jpg ./data/synthetic_human/nathan/images/04/000012.jpg
cp ./output/only_nathan/frame_12/mask/4.png ./data/synthetic_human/nathan/mask/04/000012.png
cp ./output/only_nathan/frame_12/images/5.jpg ./data/synthetic_human/nathan/images/05/000012.jpg
cp ./output/only_nathan/frame_12/mask/5.png ./data/synthetic_human/nathan/mask/05/000012.png
cp ./output/only_nathan/frame_12/images/6.jpg ./data/synthetic_human/nathan/images/06/000012.jpg
cp ./output/only_nathan/frame_12/mask/6.png ./data/synthetic_human/nathan/mask/06/000012.png
cp ./output/only_nathan/frame_12/images/7.jpg ./data/synthetic_human/nathan/images/07/000012.jpg
cp ./output/only_nathan/frame_12/mask/7.png ./data/synthetic_human/nathan/mask/07/000012.png
cp ./output/only_nathan/frame_12/images/8.jpg ./data/synthetic_human/nathan/images/08/000012.jpg
cp ./output/only_nathan/frame_12/mask/8.png ./data/synthetic_human/nathan/mask/08/000012.png
cp ./output/only_nathan/frame_12/images/9.jpg ./data/synthetic_human/nathan/images/09/000012.jpg
cp ./output/only_nathan/frame_12/mask/9.png ./data/synthetic_human/nathan/mask/09/000012.png
cp ./output/only_nathan/frame_13/images/0.jpg ./data/synthetic_human/nathan/images/00/000013.jpg
cp ./output/only_nathan/frame_13/mask/0.png ./data/synthetic_human/nathan/mask/00/000013.png
cp ./output/only_nathan/frame_13/images/1.jpg ./data/synthetic_human/nathan/images/01/000013.jpg
cp ./output/only_nathan/frame_13/mask/1.png ./data/synthetic_human/nathan/mask/01/000013.png
cp ./output/only_nathan/frame_13/images/2.jpg ./data/synthetic_human/nathan/images/02/000013.jpg
cp ./output/only_nathan/frame_13/mask/2.png ./data/synthetic_human/nathan/mask/02/000013.png
cp ./output/only_nathan/frame_13/images/3.jpg ./data/synthetic_human/nathan/images/03/000013.jpg
cp ./output/only_nathan/frame_13/mask/3.png ./data/synthetic_human/nathan/mask/03/000013.png
cp ./output/only_nathan/frame_13/images/4.jpg ./data/synthetic_human/nathan/images/04/000013.jpg
cp ./output/only_nathan/frame_13/mask/4.png ./data/synthetic_human/nathan/mask/04/000013.png
cp ./output/only_nathan/frame_13/images/5.jpg ./data/synthetic_human/nathan/images/05/000013.jpg
cp ./output/only_nathan/frame_13/mask/5.png ./data/synthetic_human/nathan/mask/05/000013.png
cp ./output/only_nathan/frame_13/images/6.jpg ./data/synthetic_human/nathan/images/06/000013.jpg
cp ./output/only_nathan/frame_13/mask/6.png ./data/synthetic_human/nathan/mask/06/000013.png
cp ./output/only_nathan/frame_13/images/7.jpg ./data/synthetic_human/nathan/images/07/000013.jpg
cp ./output/only_nathan/frame_13/mask/7.png ./data/synthetic_human/nathan/mask/07/000013.png
cp ./output/only_nathan/frame_13/images/8.jpg ./data/synthetic_human/nathan/images/08/000013.jpg
cp ./output/only_nathan/frame_13/mask/8.png ./data/synthetic_human/nathan/mask/08/000013.png
cp ./output/only_nathan/frame_13/images/9.jpg ./data/synthetic_human/nathan/images/09/000013.jpg
cp ./output/only_nathan/frame_13/mask/9.png ./data/synthetic_human/nathan/mask/09/000013.png
cp ./output/only_nathan/frame_14/images/0.jpg ./data/synthetic_human/nathan/images/00/000014.jpg
cp ./output/only_nathan/frame_14/mask/0.png ./data/synthetic_human/nathan/mask/00/000014.png
cp ./output/only_nathan/frame_14/images/1.jpg ./data/synthetic_human/nathan/images/01/000014.jpg
cp ./output/only_nathan/frame_14/mask/1.png ./data/synthetic_human/nathan/mask/01/000014.png
cp ./output/only_nathan/frame_14/images/2.jpg ./data/synthetic_human/nathan/images/02/000014.jpg
cp ./output/only_nathan/frame_14/mask/2.png ./data/synthetic_human/nathan/mask/02/000014.png
cp ./output/only_nathan/frame_14/images/3.jpg ./data/synthetic_human/nathan/images/03/000014.jpg
cp ./output/only_nathan/frame_14/mask/3.png ./data/synthetic_human/nathan/mask/03/000014.png
cp ./output/only_nathan/frame_14/images/4.jpg ./data/synthetic_human/nathan/images/04/000014.jpg
cp ./output/only_nathan/frame_14/mask/4.png ./data/synthetic_human/nathan/mask/04/000014.png
cp ./output/only_nathan/frame_14/images/5.jpg ./data/synthetic_human/nathan/images/05/000014.jpg
cp ./output/only_nathan/frame_14/mask/5.png ./data/synthetic_human/nathan/mask/05/000014.png
cp ./output/only_nathan/frame_14/images/6.jpg ./data/synthetic_human/nathan/images/06/000014.jpg
cp ./output/only_nathan/frame_14/mask/6.png ./data/synthetic_human/nathan/mask/06/000014.png
cp ./output/only_nathan/frame_14/images/7.jpg ./data/synthetic_human/nathan/images/07/000014.jpg
cp ./output/only_nathan/frame_14/mask/7.png ./data/synthetic_human/nathan/mask/07/000014.png
cp ./output/only_nathan/frame_14/images/8.jpg ./data/synthetic_human/nathan/images/08/000014.jpg
cp ./output/only_nathan/frame_14/mask/8.png ./data/synthetic_human/nathan/mask/08/000014.png
cp ./output/only_nathan/frame_14/images/9.jpg ./data/synthetic_human/nathan/images/09/000014.jpg
cp ./output/only_nathan/frame_14/mask/9.png ./data/synthetic_human/nathan/mask/09/000014.png
cp ./output/only_nathan/frame_15/images/0.jpg ./data/synthetic_human/nathan/images/00/000015.jpg
cp ./output/only_nathan/frame_15/mask/0.png ./data/synthetic_human/nathan/mask/00/000015.png
cp ./output/only_nathan/frame_15/images/1.jpg ./data/synthetic_human/nathan/images/01/000015.jpg
cp ./output/only_nathan/frame_15/mask/1.png ./data/synthetic_human/nathan/mask/01/000015.png
cp ./output/only_nathan/frame_15/images/2.jpg ./data/synthetic_human/nathan/images/02/000015.jpg
cp ./output/only_nathan/frame_15/mask/2.png ./data/synthetic_human/nathan/mask/02/000015.png
cp ./output/only_nathan/frame_15/images/3.jpg ./data/synthetic_human/nathan/images/03/000015.jpg
cp ./output/only_nathan/frame_15/mask/3.png ./data/synthetic_human/nathan/mask/03/000015.png
cp ./output/only_nathan/frame_15/images/4.jpg ./data/synthetic_human/nathan/images/04/000015.jpg
cp ./output/only_nathan/frame_15/mask/4.png ./data/synthetic_human/nathan/mask/04/000015.png
cp ./output/only_nathan/frame_15/images/5.jpg ./data/synthetic_human/nathan/images/05/000015.jpg
cp ./output/only_nathan/frame_15/mask/5.png ./data/synthetic_human/nathan/mask/05/000015.png
cp ./output/only_nathan/frame_15/images/6.jpg ./data/synthetic_human/nathan/images/06/000015.jpg
cp ./output/only_nathan/frame_15/mask/6.png ./data/synthetic_human/nathan/mask/06/000015.png
cp ./output/only_nathan/frame_15/images/7.jpg ./data/synthetic_human/nathan/images/07/000015.jpg
cp ./output/only_nathan/frame_15/mask/7.png ./data/synthetic_human/nathan/mask/07/000015.png
cp ./output/only_nathan/frame_15/images/8.jpg ./data/synthetic_human/nathan/images/08/000015.jpg
cp ./output/only_nathan/frame_15/mask/8.png ./data/synthetic_human/nathan/mask/08/000015.png
cp ./output/only_nathan/frame_15/images/9.jpg ./data/synthetic_human/nathan/images/09/000015.jpg
cp ./output/only_nathan/frame_15/mask/9.png ./data/synthetic_human/nathan/mask/09/000015.png
cp ./output/only_nathan/frame_16/images/0.jpg ./data/synthetic_human/nathan/images/00/000016.jpg
cp ./output/only_nathan/frame_16/mask/0.png ./data/synthetic_human/nathan/mask/00/000016.png
cp ./output/only_nathan/frame_16/images/1.jpg ./data/synthetic_human/nathan/images/01/000016.jpg
cp ./output/only_nathan/frame_16/mask/1.png ./data/synthetic_human/nathan/mask/01/000016.png
cp ./output/only_nathan/frame_16/images/2.jpg ./data/synthetic_human/nathan/images/02/000016.jpg
cp ./output/only_nathan/frame_16/mask/2.png ./data/synthetic_human/nathan/mask/02/000016.png
cp ./output/only_nathan/frame_16/images/3.jpg ./data/synthetic_human/nathan/images/03/000016.jpg
cp ./output/only_nathan/frame_16/mask/3.png ./data/synthetic_human/nathan/mask/03/000016.png
cp ./output/only_nathan/frame_16/images/4.jpg ./data/synthetic_human/nathan/images/04/000016.jpg
cp ./output/only_nathan/frame_16/mask/4.png ./data/synthetic_human/nathan/mask/04/000016.png
cp ./output/only_nathan/frame_16/images/5.jpg ./data/synthetic_human/nathan/images/05/000016.jpg
cp ./output/only_nathan/frame_16/mask/5.png ./data/synthetic_human/nathan/mask/05/000016.png
cp ./output/only_nathan/frame_16/images/6.jpg ./data/synthetic_human/nathan/images/06/000016.jpg
cp ./output/only_nathan/frame_16/mask/6.png ./data/synthetic_human/nathan/mask/06/000016.png
cp ./output/only_nathan/frame_16/images/7.jpg ./data/synthetic_human/nathan/images/07/000016.jpg
cp ./output/only_nathan/frame_16/mask/7.png ./data/synthetic_human/nathan/mask/07/000016.png
cp ./output/only_nathan/frame_16/images/8.jpg ./data/synthetic_human/nathan/images/08/000016.jpg
cp ./output/only_nathan/frame_16/mask/8.png ./data/synthetic_human/nathan/mask/08/000016.png
cp ./output/only_nathan/frame_16/images/9.jpg ./data/synthetic_human/nathan/images/09/000016.jpg
cp ./output/only_nathan/frame_16/mask/9.png ./data/synthetic_human/nathan/mask/09/000016.png
cp ./output/only_nathan/frame_17/images/0.jpg ./data/synthetic_human/nathan/images/00/000017.jpg
cp ./output/only_nathan/frame_17/mask/0.png ./data/synthetic_human/nathan/mask/00/000017.png
cp ./output/only_nathan/frame_17/images/1.jpg ./data/synthetic_human/nathan/images/01/000017.jpg
cp ./output/only_nathan/frame_17/mask/1.png ./data/synthetic_human/nathan/mask/01/000017.png
cp ./output/only_nathan/frame_17/images/2.jpg ./data/synthetic_human/nathan/images/02/000017.jpg
cp ./output/only_nathan/frame_17/mask/2.png ./data/synthetic_human/nathan/mask/02/000017.png
cp ./output/only_nathan/frame_17/images/3.jpg ./data/synthetic_human/nathan/images/03/000017.jpg
cp ./output/only_nathan/frame_17/mask/3.png ./data/synthetic_human/nathan/mask/03/000017.png
cp ./output/only_nathan/frame_17/images/4.jpg ./data/synthetic_human/nathan/images/04/000017.jpg
cp ./output/only_nathan/frame_17/mask/4.png ./data/synthetic_human/nathan/mask/04/000017.png
cp ./output/only_nathan/frame_17/images/5.jpg ./data/synthetic_human/nathan/images/05/000017.jpg
cp ./output/only_nathan/frame_17/mask/5.png ./data/synthetic_human/nathan/mask/05/000017.png
cp ./output/only_nathan/frame_17/images/6.jpg ./data/synthetic_human/nathan/images/06/000017.jpg
cp ./output/only_nathan/frame_17/mask/6.png ./data/synthetic_human/nathan/mask/06/000017.png
cp ./output/only_nathan/frame_17/images/7.jpg ./data/synthetic_human/nathan/images/07/000017.jpg
cp ./output/only_nathan/frame_17/mask/7.png ./data/synthetic_human/nathan/mask/07/000017.png
cp ./output/only_nathan/frame_17/images/8.jpg ./data/synthetic_human/nathan/images/08/000017.jpg
cp ./output/only_nathan/frame_17/mask/8.png ./data/synthetic_human/nathan/mask/08/000017.png
cp ./output/only_nathan/frame_17/images/9.jpg ./data/synthetic_human/nathan/images/09/000017.jpg
cp ./output/only_nathan/frame_17/mask/9.png ./data/synthetic_human/nathan/mask/09/000017.png
cp ./output/only_nathan/frame_18/images/0.jpg ./data/synthetic_human/nathan/images/00/000018.jpg
cp ./output/only_nathan/frame_18/mask/0.png ./data/synthetic_human/nathan/mask/00/000018.png
cp ./output/only_nathan/frame_18/images/1.jpg ./data/synthetic_human/nathan/images/01/000018.jpg
cp ./output/only_nathan/frame_18/mask/1.png ./data/synthetic_human/nathan/mask/01/000018.png
cp ./output/only_nathan/frame_18/images/2.jpg ./data/synthetic_human/nathan/images/02/000018.jpg
cp ./output/only_nathan/frame_18/mask/2.png ./data/synthetic_human/nathan/mask/02/000018.png
cp ./output/only_nathan/frame_18/images/3.jpg ./data/synthetic_human/nathan/images/03/000018.jpg
cp ./output/only_nathan/frame_18/mask/3.png ./data/synthetic_human/nathan/mask/03/000018.png
cp ./output/only_nathan/frame_18/images/4.jpg ./data/synthetic_human/nathan/images/04/000018.jpg
cp ./output/only_nathan/frame_18/mask/4.png ./data/synthetic_human/nathan/mask/04/000018.png
cp ./output/only_nathan/frame_18/images/5.jpg ./data/synthetic_human/nathan/images/05/000018.jpg
cp ./output/only_nathan/frame_18/mask/5.png ./data/synthetic_human/nathan/mask/05/000018.png
cp ./output/only_nathan/frame_18/images/6.jpg ./data/synthetic_human/nathan/images/06/000018.jpg
cp ./output/only_nathan/frame_18/mask/6.png ./data/synthetic_human/nathan/mask/06/000018.png
cp ./output/only_nathan/frame_18/images/7.jpg ./data/synthetic_human/nathan/images/07/000018.jpg
cp ./output/only_nathan/frame_18/mask/7.png ./data/synthetic_human/nathan/mask/07/000018.png
cp ./output/only_nathan/frame_18/images/8.jpg ./data/synthetic_human/nathan/images/08/000018.jpg
cp ./output/only_nathan/frame_18/mask/8.png ./data/synthetic_human/nathan/mask/08/000018.png
cp ./output/only_nathan/frame_18/images/9.jpg ./data/synthetic_human/nathan/images/09/000018.jpg
cp ./output/only_nathan/frame_18/mask/9.png ./data/synthetic_human/nathan/mask/09/000018.png
cp ./output/only_nathan/frame_19/images/0.jpg ./data/synthetic_human/nathan/images/00/000019.jpg
cp ./output/only_nathan/frame_19/mask/0.png ./data/synthetic_human/nathan/mask/00/000019.png
cp ./output/only_nathan/frame_19/images/1.jpg ./data/synthetic_human/nathan/images/01/000019.jpg
cp ./output/only_nathan/frame_19/mask/1.png ./data/synthetic_human/nathan/mask/01/000019.png
cp ./output/only_nathan/frame_19/images/2.jpg ./data/synthetic_human/nathan/images/02/000019.jpg
cp ./output/only_nathan/frame_19/mask/2.png ./data/synthetic_human/nathan/mask/02/000019.png
cp ./output/only_nathan/frame_19/images/3.jpg ./data/synthetic_human/nathan/images/03/000019.jpg
cp ./output/only_nathan/frame_19/mask/3.png ./data/synthetic_human/nathan/mask/03/000019.png
cp ./output/only_nathan/frame_19/images/4.jpg ./data/synthetic_human/nathan/images/04/000019.jpg
cp ./output/only_nathan/frame_19/mask/4.png ./data/synthetic_human/nathan/mask/04/000019.png
cp ./output/only_nathan/frame_19/images/5.jpg ./data/synthetic_human/nathan/images/05/000019.jpg
cp ./output/only_nathan/frame_19/mask/5.png ./data/synthetic_human/nathan/mask/05/000019.png
cp ./output/only_nathan/frame_19/images/6.jpg ./data/synthetic_human/nathan/images/06/000019.jpg
cp ./output/only_nathan/frame_19/mask/6.png ./data/synthetic_human/nathan/mask/06/000019.png
cp ./output/only_nathan/frame_19/images/7.jpg ./data/synthetic_human/nathan/images/07/000019.jpg
cp ./output/only_nathan/frame_19/mask/7.png ./data/synthetic_human/nathan/mask/07/000019.png
cp ./output/only_nathan/frame_19/images/8.jpg ./data/synthetic_human/nathan/images/08/000019.jpg
cp ./output/only_nathan/frame_19/mask/8.png ./data/synthetic_human/nathan/mask/08/000019.png
cp ./output/only_nathan/frame_19/images/9.jpg ./data/synthetic_human/nathan/images/09/000019.jpg
cp ./output/only_nathan/frame_19/mask/9.png ./data/synthetic_human/nathan/mask/09/000019.png
cp ./output/only_nathan/frame_20/images/0.jpg ./data/synthetic_human/nathan/images/00/000020.jpg
cp ./output/only_nathan/frame_20/mask/0.png ./data/synthetic_human/nathan/mask/00/000020.png
cp ./output/only_nathan/frame_20/images/1.jpg ./data/synthetic_human/nathan/images/01/000020.jpg
cp ./output/only_nathan/frame_20/mask/1.png ./data/synthetic_human/nathan/mask/01/000020.png
cp ./output/only_nathan/frame_20/images/2.jpg ./data/synthetic_human/nathan/images/02/000020.jpg
cp ./output/only_nathan/frame_20/mask/2.png ./data/synthetic_human/nathan/mask/02/000020.png
cp ./output/only_nathan/frame_20/images/3.jpg ./data/synthetic_human/nathan/images/03/000020.jpg
cp ./output/only_nathan/frame_20/mask/3.png ./data/synthetic_human/nathan/mask/03/000020.png
cp ./output/only_nathan/frame_20/images/4.jpg ./data/synthetic_human/nathan/images/04/000020.jpg
cp ./output/only_nathan/frame_20/mask/4.png ./data/synthetic_human/nathan/mask/04/000020.png
cp ./output/only_nathan/frame_20/images/5.jpg ./data/synthetic_human/nathan/images/05/000020.jpg
cp ./output/only_nathan/frame_20/mask/5.png ./data/synthetic_human/nathan/mask/05/000020.png
cp ./output/only_nathan/frame_20/images/6.jpg ./data/synthetic_human/nathan/images/06/000020.jpg
cp ./output/only_nathan/frame_20/mask/6.png ./data/synthetic_human/nathan/mask/06/000020.png
cp ./output/only_nathan/frame_20/images/7.jpg ./data/synthetic_human/nathan/images/07/000020.jpg
cp ./output/only_nathan/frame_20/mask/7.png ./data/synthetic_human/nathan/mask/07/000020.png
cp ./output/only_nathan/frame_20/images/8.jpg ./data/synthetic_human/nathan/images/08/000020.jpg
cp ./output/only_nathan/frame_20/mask/8.png ./data/synthetic_human/nathan/mask/08/000020.png
cp ./output/only_nathan/frame_20/images/9.jpg ./data/synthetic_human/nathan/images/09/000020.jpg
cp ./output/only_nathan/frame_20/mask/9.png ./data/synthetic_human/nathan/mask/09/000020.png
cp ./output/only_nathan/frame_21/images/0.jpg ./data/synthetic_human/nathan/images/00/000021.jpg
cp ./output/only_nathan/frame_21/mask/0.png ./data/synthetic_human/nathan/mask/00/000021.png
cp ./output/only_nathan/frame_21/images/1.jpg ./data/synthetic_human/nathan/images/01/000021.jpg
cp ./output/only_nathan/frame_21/mask/1.png ./data/synthetic_human/nathan/mask/01/000021.png
cp ./output/only_nathan/frame_21/images/2.jpg ./data/synthetic_human/nathan/images/02/000021.jpg
cp ./output/only_nathan/frame_21/mask/2.png ./data/synthetic_human/nathan/mask/02/000021.png
cp ./output/only_nathan/frame_21/images/3.jpg ./data/synthetic_human/nathan/images/03/000021.jpg
cp ./output/only_nathan/frame_21/mask/3.png ./data/synthetic_human/nathan/mask/03/000021.png
cp ./output/only_nathan/frame_21/images/4.jpg ./data/synthetic_human/nathan/images/04/000021.jpg
cp ./output/only_nathan/frame_21/mask/4.png ./data/synthetic_human/nathan/mask/04/000021.png
cp ./output/only_nathan/frame_21/images/5.jpg ./data/synthetic_human/nathan/images/05/000021.jpg
cp ./output/only_nathan/frame_21/mask/5.png ./data/synthetic_human/nathan/mask/05/000021.png
cp ./output/only_nathan/frame_21/images/6.jpg ./data/synthetic_human/nathan/images/06/000021.jpg
cp ./output/only_nathan/frame_21/mask/6.png ./data/synthetic_human/nathan/mask/06/000021.png
cp ./output/only_nathan/frame_21/images/7.jpg ./data/synthetic_human/nathan/images/07/000021.jpg
cp ./output/only_nathan/frame_21/mask/7.png ./data/synthetic_human/nathan/mask/07/000021.png
cp ./output/only_nathan/frame_21/images/8.jpg ./data/synthetic_human/nathan/images/08/000021.jpg
cp ./output/only_nathan/frame_21/mask/8.png ./data/synthetic_human/nathan/mask/08/000021.png
cp ./output/only_nathan/frame_21/images/9.jpg ./data/synthetic_human/nathan/images/09/000021.jpg
cp ./output/only_nathan/frame_21/mask/9.png ./data/synthetic_human/nathan/mask/09/000021.png
cp ./output/only_nathan/frame_22/images/0.jpg ./data/synthetic_human/nathan/images/00/000022.jpg
cp ./output/only_nathan/frame_22/mask/0.png ./data/synthetic_human/nathan/mask/00/000022.png
cp ./output/only_nathan/frame_22/images/1.jpg ./data/synthetic_human/nathan/images/01/000022.jpg
cp ./output/only_nathan/frame_22/mask/1.png ./data/synthetic_human/nathan/mask/01/000022.png
cp ./output/only_nathan/frame_22/images/2.jpg ./data/synthetic_human/nathan/images/02/000022.jpg
cp ./output/only_nathan/frame_22/mask/2.png ./data/synthetic_human/nathan/mask/02/000022.png
cp ./output/only_nathan/frame_22/images/3.jpg ./data/synthetic_human/nathan/images/03/000022.jpg
cp ./output/only_nathan/frame_22/mask/3.png ./data/synthetic_human/nathan/mask/03/000022.png
cp ./output/only_nathan/frame_22/images/4.jpg ./data/synthetic_human/nathan/images/04/000022.jpg
cp ./output/only_nathan/frame_22/mask/4.png ./data/synthetic_human/nathan/mask/04/000022.png
cp ./output/only_nathan/frame_22/images/5.jpg ./data/synthetic_human/nathan/images/05/000022.jpg
cp ./output/only_nathan/frame_22/mask/5.png ./data/synthetic_human/nathan/mask/05/000022.png
cp ./output/only_nathan/frame_22/images/6.jpg ./data/synthetic_human/nathan/images/06/000022.jpg
cp ./output/only_nathan/frame_22/mask/6.png ./data/synthetic_human/nathan/mask/06/000022.png
cp ./output/only_nathan/frame_22/images/7.jpg ./data/synthetic_human/nathan/images/07/000022.jpg
cp ./output/only_nathan/frame_22/mask/7.png ./data/synthetic_human/nathan/mask/07/000022.png
cp ./output/only_nathan/frame_22/images/8.jpg ./data/synthetic_human/nathan/images/08/000022.jpg
cp ./output/only_nathan/frame_22/mask/8.png ./data/synthetic_human/nathan/mask/08/000022.png
cp ./output/only_nathan/frame_22/images/9.jpg ./data/synthetic_human/nathan/images/09/000022.jpg
cp ./output/only_nathan/frame_22/mask/9.png ./data/synthetic_human/nathan/mask/09/000022.png
cp ./output/only_nathan/frame_23/images/0.jpg ./data/synthetic_human/nathan/images/00/000023.jpg
cp ./output/only_nathan/frame_23/mask/0.png ./data/synthetic_human/nathan/mask/00/000023.png
cp ./output/only_nathan/frame_23/images/1.jpg ./data/synthetic_human/nathan/images/01/000023.jpg
cp ./output/only_nathan/frame_23/mask/1.png ./data/synthetic_human/nathan/mask/01/000023.png
cp ./output/only_nathan/frame_23/images/2.jpg ./data/synthetic_human/nathan/images/02/000023.jpg
cp ./output/only_nathan/frame_23/mask/2.png ./data/synthetic_human/nathan/mask/02/000023.png
cp ./output/only_nathan/frame_23/images/3.jpg ./data/synthetic_human/nathan/images/03/000023.jpg
cp ./output/only_nathan/frame_23/mask/3.png ./data/synthetic_human/nathan/mask/03/000023.png
cp ./output/only_nathan/frame_23/images/4.jpg ./data/synthetic_human/nathan/images/04/000023.jpg
cp ./output/only_nathan/frame_23/mask/4.png ./data/synthetic_human/nathan/mask/04/000023.png
cp ./output/only_nathan/frame_23/images/5.jpg ./data/synthetic_human/nathan/images/05/000023.jpg
cp ./output/only_nathan/frame_23/mask/5.png ./data/synthetic_human/nathan/mask/05/000023.png
cp ./output/only_nathan/frame_23/images/6.jpg ./data/synthetic_human/nathan/images/06/000023.jpg
cp ./output/only_nathan/frame_23/mask/6.png ./data/synthetic_human/nathan/mask/06/000023.png
cp ./output/only_nathan/frame_23/images/7.jpg ./data/synthetic_human/nathan/images/07/000023.jpg
cp ./output/only_nathan/frame_23/mask/7.png ./data/synthetic_human/nathan/mask/07/000023.png
cp ./output/only_nathan/frame_23/images/8.jpg ./data/synthetic_human/nathan/images/08/000023.jpg
cp ./output/only_nathan/frame_23/mask/8.png ./data/synthetic_human/nathan/mask/08/000023.png
cp ./output/only_nathan/frame_23/images/9.jpg ./data/synthetic_human/nathan/images/09/000023.jpg
cp ./output/only_nathan/frame_23/mask/9.png ./data/synthetic_human/nathan/mask/09/000023.png
cp ./output/only_nathan/frame_24/images/0.jpg ./data/synthetic_human/nathan/images/00/000024.jpg
cp ./output/only_nathan/frame_24/mask/0.png ./data/synthetic_human/nathan/mask/00/000024.png
cp ./output/only_nathan/frame_24/images/1.jpg ./data/synthetic_human/nathan/images/01/000024.jpg
cp ./output/only_nathan/frame_24/mask/1.png ./data/synthetic_human/nathan/mask/01/000024.png
cp ./output/only_nathan/frame_24/images/2.jpg ./data/synthetic_human/nathan/images/02/000024.jpg
cp ./output/only_nathan/frame_24/mask/2.png ./data/synthetic_human/nathan/mask/02/000024.png
cp ./output/only_nathan/frame_24/images/3.jpg ./data/synthetic_human/nathan/images/03/000024.jpg
cp ./output/only_nathan/frame_24/mask/3.png ./data/synthetic_human/nathan/mask/03/000024.png
cp ./output/only_nathan/frame_24/images/4.jpg ./data/synthetic_human/nathan/images/04/000024.jpg
cp ./output/only_nathan/frame_24/mask/4.png ./data/synthetic_human/nathan/mask/04/000024.png
cp ./output/only_nathan/frame_24/images/5.jpg ./data/synthetic_human/nathan/images/05/000024.jpg
cp ./output/only_nathan/frame_24/mask/5.png ./data/synthetic_human/nathan/mask/05/000024.png
cp ./output/only_nathan/frame_24/images/6.jpg ./data/synthetic_human/nathan/images/06/000024.jpg
cp ./output/only_nathan/frame_24/mask/6.png ./data/synthetic_human/nathan/mask/06/000024.png
cp ./output/only_nathan/frame_24/images/7.jpg ./data/synthetic_human/nathan/images/07/000024.jpg
cp ./output/only_nathan/frame_24/mask/7.png ./data/synthetic_human/nathan/mask/07/000024.png
cp ./output/only_nathan/frame_24/images/8.jpg ./data/synthetic_human/nathan/images/08/000024.jpg
cp ./output/only_nathan/frame_24/mask/8.png ./data/synthetic_human/nathan/mask/08/000024.png
cp ./output/only_nathan/frame_24/images/9.jpg ./data/synthetic_human/nathan/images/09/000024.jpg
cp ./output/only_nathan/frame_24/mask/9.png ./data/synthetic_human/nathan/mask/09/000024.png
cp ./output/only_nathan/frame_25/images/0.jpg ./data/synthetic_human/nathan/images/00/000025.jpg
cp ./output/only_nathan/frame_25/mask/0.png ./data/synthetic_human/nathan/mask/00/000025.png
cp ./output/only_nathan/frame_25/images/1.jpg ./data/synthetic_human/nathan/images/01/000025.jpg
cp ./output/only_nathan/frame_25/mask/1.png ./data/synthetic_human/nathan/mask/01/000025.png
cp ./output/only_nathan/frame_25/images/2.jpg ./data/synthetic_human/nathan/images/02/000025.jpg
cp ./output/only_nathan/frame_25/mask/2.png ./data/synthetic_human/nathan/mask/02/000025.png
cp ./output/only_nathan/frame_25/images/3.jpg ./data/synthetic_human/nathan/images/03/000025.jpg
cp ./output/only_nathan/frame_25/mask/3.png ./data/synthetic_human/nathan/mask/03/000025.png
cp ./output/only_nathan/frame_25/images/4.jpg ./data/synthetic_human/nathan/images/04/000025.jpg
cp ./output/only_nathan/frame_25/mask/4.png ./data/synthetic_human/nathan/mask/04/000025.png
cp ./output/only_nathan/frame_25/images/5.jpg ./data/synthetic_human/nathan/images/05/000025.jpg
cp ./output/only_nathan/frame_25/mask/5.png ./data/synthetic_human/nathan/mask/05/000025.png
cp ./output/only_nathan/frame_25/images/6.jpg ./data/synthetic_human/nathan/images/06/000025.jpg
cp ./output/only_nathan/frame_25/mask/6.png ./data/synthetic_human/nathan/mask/06/000025.png
cp ./output/only_nathan/frame_25/images/7.jpg ./data/synthetic_human/nathan/images/07/000025.jpg
cp ./output/only_nathan/frame_25/mask/7.png ./data/synthetic_human/nathan/mask/07/000025.png
cp ./output/only_nathan/frame_25/images/8.jpg ./data/synthetic_human/nathan/images/08/000025.jpg
cp ./output/only_nathan/frame_25/mask/8.png ./data/synthetic_human/nathan/mask/08/000025.png
cp ./output/only_nathan/frame_25/images/9.jpg ./data/synthetic_human/nathan/images/09/000025.jpg
cp ./output/only_nathan/frame_25/mask/9.png ./data/synthetic_human/nathan/mask/09/000025.png
cp ./output/only_nathan/frame_26/images/0.jpg ./data/synthetic_human/nathan/images/00/000026.jpg
cp ./output/only_nathan/frame_26/mask/0.png ./data/synthetic_human/nathan/mask/00/000026.png
cp ./output/only_nathan/frame_26/images/1.jpg ./data/synthetic_human/nathan/images/01/000026.jpg
cp ./output/only_nathan/frame_26/mask/1.png ./data/synthetic_human/nathan/mask/01/000026.png
cp ./output/only_nathan/frame_26/images/2.jpg ./data/synthetic_human/nathan/images/02/000026.jpg
cp ./output/only_nathan/frame_26/mask/2.png ./data/synthetic_human/nathan/mask/02/000026.png
cp ./output/only_nathan/frame_26/images/3.jpg ./data/synthetic_human/nathan/images/03/000026.jpg
cp ./output/only_nathan/frame_26/mask/3.png ./data/synthetic_human/nathan/mask/03/000026.png
cp ./output/only_nathan/frame_26/images/4.jpg ./data/synthetic_human/nathan/images/04/000026.jpg
cp ./output/only_nathan/frame_26/mask/4.png ./data/synthetic_human/nathan/mask/04/000026.png
cp ./output/only_nathan/frame_26/images/5.jpg ./data/synthetic_human/nathan/images/05/000026.jpg
cp ./output/only_nathan/frame_26/mask/5.png ./data/synthetic_human/nathan/mask/05/000026.png
cp ./output/only_nathan/frame_26/images/6.jpg ./data/synthetic_human/nathan/images/06/000026.jpg
cp ./output/only_nathan/frame_26/mask/6.png ./data/synthetic_human/nathan/mask/06/000026.png
cp ./output/only_nathan/frame_26/images/7.jpg ./data/synthetic_human/nathan/images/07/000026.jpg
cp ./output/only_nathan/frame_26/mask/7.png ./data/synthetic_human/nathan/mask/07/000026.png
cp ./output/only_nathan/frame_26/images/8.jpg ./data/synthetic_human/nathan/images/08/000026.jpg
cp ./output/only_nathan/frame_26/mask/8.png ./data/synthetic_human/nathan/mask/08/000026.png
cp ./output/only_nathan/frame_26/images/9.jpg ./data/synthetic_human/nathan/images/09/000026.jpg
cp ./output/only_nathan/frame_26/mask/9.png ./data/synthetic_human/nathan/mask/09/000026.png
cp ./output/only_nathan/frame_27/images/0.jpg ./data/synthetic_human/nathan/images/00/000027.jpg
cp ./output/only_nathan/frame_27/mask/0.png ./data/synthetic_human/nathan/mask/00/000027.png
cp ./output/only_nathan/frame_27/images/1.jpg ./data/synthetic_human/nathan/images/01/000027.jpg
cp ./output/only_nathan/frame_27/mask/1.png ./data/synthetic_human/nathan/mask/01/000027.png
cp ./output/only_nathan/frame_27/images/2.jpg ./data/synthetic_human/nathan/images/02/000027.jpg
cp ./output/only_nathan/frame_27/mask/2.png ./data/synthetic_human/nathan/mask/02/000027.png
cp ./output/only_nathan/frame_27/images/3.jpg ./data/synthetic_human/nathan/images/03/000027.jpg
cp ./output/only_nathan/frame_27/mask/3.png ./data/synthetic_human/nathan/mask/03/000027.png
cp ./output/only_nathan/frame_27/images/4.jpg ./data/synthetic_human/nathan/images/04/000027.jpg
cp ./output/only_nathan/frame_27/mask/4.png ./data/synthetic_human/nathan/mask/04/000027.png
cp ./output/only_nathan/frame_27/images/5.jpg ./data/synthetic_human/nathan/images/05/000027.jpg
cp ./output/only_nathan/frame_27/mask/5.png ./data/synthetic_human/nathan/mask/05/000027.png
cp ./output/only_nathan/frame_27/images/6.jpg ./data/synthetic_human/nathan/images/06/000027.jpg
cp ./output/only_nathan/frame_27/mask/6.png ./data/synthetic_human/nathan/mask/06/000027.png
cp ./output/only_nathan/frame_27/images/7.jpg ./data/synthetic_human/nathan/images/07/000027.jpg
cp ./output/only_nathan/frame_27/mask/7.png ./data/synthetic_human/nathan/mask/07/000027.png
cp ./output/only_nathan/frame_27/images/8.jpg ./data/synthetic_human/nathan/images/08/000027.jpg
cp ./output/only_nathan/frame_27/mask/8.png ./data/synthetic_human/nathan/mask/08/000027.png
cp ./output/only_nathan/frame_27/images/9.jpg ./data/synthetic_human/nathan/images/09/000027.jpg
cp ./output/only_nathan/frame_27/mask/9.png ./data/synthetic_human/nathan/mask/09/000027.png
cp ./output/only_nathan/frame_28/images/0.jpg ./data/synthetic_human/nathan/images/00/000028.jpg
cp ./output/only_nathan/frame_28/mask/0.png ./data/synthetic_human/nathan/mask/00/000028.png
cp ./output/only_nathan/frame_28/images/1.jpg ./data/synthetic_human/nathan/images/01/000028.jpg
cp ./output/only_nathan/frame_28/mask/1.png ./data/synthetic_human/nathan/mask/01/000028.png
cp ./output/only_nathan/frame_28/images/2.jpg ./data/synthetic_human/nathan/images/02/000028.jpg
cp ./output/only_nathan/frame_28/mask/2.png ./data/synthetic_human/nathan/mask/02/000028.png
cp ./output/only_nathan/frame_28/images/3.jpg ./data/synthetic_human/nathan/images/03/000028.jpg
cp ./output/only_nathan/frame_28/mask/3.png ./data/synthetic_human/nathan/mask/03/000028.png
cp ./output/only_nathan/frame_28/images/4.jpg ./data/synthetic_human/nathan/images/04/000028.jpg
cp ./output/only_nathan/frame_28/mask/4.png ./data/synthetic_human/nathan/mask/04/000028.png
cp ./output/only_nathan/frame_28/images/5.jpg ./data/synthetic_human/nathan/images/05/000028.jpg
cp ./output/only_nathan/frame_28/mask/5.png ./data/synthetic_human/nathan/mask/05/000028.png
cp ./output/only_nathan/frame_28/images/6.jpg ./data/synthetic_human/nathan/images/06/000028.jpg
cp ./output/only_nathan/frame_28/mask/6.png ./data/synthetic_human/nathan/mask/06/000028.png
cp ./output/only_nathan/frame_28/images/7.jpg ./data/synthetic_human/nathan/images/07/000028.jpg
cp ./output/only_nathan/frame_28/mask/7.png ./data/synthetic_human/nathan/mask/07/000028.png
cp ./output/only_nathan/frame_28/images/8.jpg ./data/synthetic_human/nathan/images/08/000028.jpg
cp ./output/only_nathan/frame_28/mask/8.png ./data/synthetic_human/nathan/mask/08/000028.png
cp ./output/only_nathan/frame_28/images/9.jpg ./data/synthetic_human/nathan/images/09/000028.jpg
cp ./output/only_nathan/frame_28/mask/9.png ./data/synthetic_human/nathan/mask/09/000028.png
cp ./output/only_nathan/frame_29/images/0.jpg ./data/synthetic_human/nathan/images/00/000029.jpg
cp ./output/only_nathan/frame_29/mask/0.png ./data/synthetic_human/nathan/mask/00/000029.png
cp ./output/only_nathan/frame_29/images/1.jpg ./data/synthetic_human/nathan/images/01/000029.jpg
cp ./output/only_nathan/frame_29/mask/1.png ./data/synthetic_human/nathan/mask/01/000029.png
cp ./output/only_nathan/frame_29/images/2.jpg ./data/synthetic_human/nathan/images/02/000029.jpg
cp ./output/only_nathan/frame_29/mask/2.png ./data/synthetic_human/nathan/mask/02/000029.png
cp ./output/only_nathan/frame_29/images/3.jpg ./data/synthetic_human/nathan/images/03/000029.jpg
cp ./output/only_nathan/frame_29/mask/3.png ./data/synthetic_human/nathan/mask/03/000029.png
cp ./output/only_nathan/frame_29/images/4.jpg ./data/synthetic_human/nathan/images/04/000029.jpg
cp ./output/only_nathan/frame_29/mask/4.png ./data/synthetic_human/nathan/mask/04/000029.png
cp ./output/only_nathan/frame_29/images/5.jpg ./data/synthetic_human/nathan/images/05/000029.jpg
cp ./output/only_nathan/frame_29/mask/5.png ./data/synthetic_human/nathan/mask/05/000029.png
cp ./output/only_nathan/frame_29/images/6.jpg ./data/synthetic_human/nathan/images/06/000029.jpg
cp ./output/only_nathan/frame_29/mask/6.png ./data/synthetic_human/nathan/mask/06/000029.png
cp ./output/only_nathan/frame_29/images/7.jpg ./data/synthetic_human/nathan/images/07/000029.jpg
cp ./output/only_nathan/frame_29/mask/7.png ./data/synthetic_human/nathan/mask/07/000029.png
cp ./output/only_nathan/frame_29/images/8.jpg ./data/synthetic_human/nathan/images/08/000029.jpg
cp ./output/only_nathan/frame_29/mask/8.png ./data/synthetic_human/nathan/mask/08/000029.png
cp ./output/only_nathan/frame_29/images/9.jpg ./data/synthetic_human/nathan/images/09/000029.jpg
cp ./output/only_nathan/frame_29/mask/9.png ./data/synthetic_human/nathan/mask/09/000029.png
cp ./output/only_nathan/frame_30/images/0.jpg ./data/synthetic_human/nathan/images/00/000030.jpg
cp ./output/only_nathan/frame_30/mask/0.png ./data/synthetic_human/nathan/mask/00/000030.png
cp ./output/only_nathan/frame_30/images/1.jpg ./data/synthetic_human/nathan/images/01/000030.jpg
cp ./output/only_nathan/frame_30/mask/1.png ./data/synthetic_human/nathan/mask/01/000030.png
cp ./output/only_nathan/frame_30/images/2.jpg ./data/synthetic_human/nathan/images/02/000030.jpg
cp ./output/only_nathan/frame_30/mask/2.png ./data/synthetic_human/nathan/mask/02/000030.png
cp ./output/only_nathan/frame_30/images/3.jpg ./data/synthetic_human/nathan/images/03/000030.jpg
cp ./output/only_nathan/frame_30/mask/3.png ./data/synthetic_human/nathan/mask/03/000030.png
cp ./output/only_nathan/frame_30/images/4.jpg ./data/synthetic_human/nathan/images/04/000030.jpg
cp ./output/only_nathan/frame_30/mask/4.png ./data/synthetic_human/nathan/mask/04/000030.png
cp ./output/only_nathan/frame_30/images/5.jpg ./data/synthetic_human/nathan/images/05/000030.jpg
cp ./output/only_nathan/frame_30/mask/5.png ./data/synthetic_human/nathan/mask/05/000030.png
cp ./output/only_nathan/frame_30/images/6.jpg ./data/synthetic_human/nathan/images/06/000030.jpg
cp ./output/only_nathan/frame_30/mask/6.png ./data/synthetic_human/nathan/mask/06/000030.png
cp ./output/only_nathan/frame_30/images/7.jpg ./data/synthetic_human/nathan/images/07/000030.jpg
cp ./output/only_nathan/frame_30/mask/7.png ./data/synthetic_human/nathan/mask/07/000030.png
cp ./output/only_nathan/frame_30/images/8.jpg ./data/synthetic_human/nathan/images/08/000030.jpg
cp ./output/only_nathan/frame_30/mask/8.png ./data/synthetic_human/nathan/mask/08/000030.png
cp ./output/only_nathan/frame_30/images/9.jpg ./data/synthetic_human/nathan/images/09/000030.jpg
cp ./output/only_nathan/frame_30/mask/9.png ./data/synthetic_human/nathan/mask/09/000030.png
